version: "3.8"
services:
  p3x:
    image: patrikx3/p3x-redis-ui:latest
    container_name: p3x
    ports:
      - "7843:7843"
    restart: always
    privileged: true
    volumes:
      - ./data/settings:/settings
